# config/config.yaml (o la ruta que prefieras)

# --- Trading Parameters ---
trading:
  symbol: "SOLUSDT"
  timeframe: "5m"
  use_testnet: true
  min_candles_for_bot_start: 51
  trade_cooldown_after_close_seconds: 60
  sentiment_refresh_cooldown_seconds: 600
  # Define el máximo de reintentos para obtener el estado de una orden
  order_status_max_retries: 7
  # Define el delay inicial en segundos para reintentar obtener el estado de una orden
  order_status_initial_delay: 0.5


# --- Binance API ---
# Es MÁS SEGURO cargar estos desde variables de entorno o un archivo .env no versionado.
# El config_loader.py puede leerlos desde el entorno si no se especifican aquí.
binance:
  api_key: "" # Dejar vacío para cargar desde ENV, o especificar si es seguro
  api_secret: "" # Dejar vacío para cargar desde ENV

# --- Risk Management Parameters (para AdvancedRiskManager) ---
risk_management:
  base_risk_per_trade: 0.02      # Ej: 1% del balance disponible por operación
  max_risk_per_trade: 0.04       # Ej: Máximo 2%
  min_risk_per_trade: 0.005      # Ej: Mínimo 0.5%
  atr_sl_multiplier: 1.5
  atr_tp_multiplier: 2.0         # Esto es para un R:R objetivo, ej., si SL es 1.5*ATR, TP a 3.0*ATR da R:R=2
  min_reward_risk_ratio: 1.5
  target_reward_risk_ratio: 2.0
  max_daily_loss_pct: 0.05       # Ej: 5% del balance total como pérdida máxima diaria
  max_consecutive_losses: 6
  max_trades_per_day: 60
  # Los factores de ajuste dinámico (volatility, performance, etc.) se calculan en el RiskManager,
  # pero los valores base o los límites podrían estar aquí si se desea.

# --- LLM Configuration (Defaults para EnhancedBaseLLMAgent) ---
llm:
  default_timeout: 90 # Segundos, aumentado para modelos más lentos o visión
  default_temperature: 0.15
  default_max_tokens: 1500
  # La configuración específica del modelo por agente (nombre, supports_tools, etc.)
  # seguirá en config/modern_models.py por ahora para mantener esa lógica especializada allí.

# --- Tools Configuration ---
tools:
  news_scraper:
    # Dejar vacío para cargar desde la variable de entorno CRYPTOPANIC_TOKENS
    # o especificar una lista de tokens aquí si es seguro: ["token1", "token2"]
    cryptopanic_api_tokens: [a1125cef0b98fef468f801cf059a6472d306464f]
  chart_generator:
    save_charts_to_disk: true
    charts_dir: "logs/charts" # Directorio donde se guardan los gráficos

# --- Logging Configuration ---
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/fenix_live_trading.log"

# --- Technical Tools Configuration ---
technical_tools:
  maxlen_buffer: 100 # MAXLEN para close_buf, etc.
  min_candles_for_reliable_calc: 51

# --- Agent Specific Configs (Opcional, si no se manejan internamente o por ModelManager) ---
# agents:
#   sentiment_analyst:
#     max_texts_to_fetch_per_source: 20
#     min_text_quality_threshold: 0.3
#   technical_analyst:
#     sequence_length_llm4fts: 25
